### ISSUE TITLE
Timeout occurs when asking for info from device

### ISSUE THREAD

**Issue by jh510** [labstreaminglayer/App-Zephyr#6]
Hi,

I am able to connect to the device (blue light flashes), but I never get any data due to a timeout on line 278 infos = await link.get_infos(). I am not running a conda environment, but have installed the correct dependencies.  

Here is the logging info:
2020-11-17 08:53:26,929 INFO: starting up...
2020-11-17 08:53:26,930 INFO: Connecting to device A4:34:F1:EA:1C:BD...
2020-11-17 08:53:27.126 Python[27662:35700116] instantiateOnDevice for regular
2020-11-17 08:53:28.301 Python[27662:35700116] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.
2020-11-17 08:53:36,936 ERROR: Operation timed out: Waiting for device response to GetSerialNumber timed out.

**Comment by chkothe** [comment]
Hi, we haven't observed that kind of behavior during our testing (usually the device responds in 1-3 seconds). You can provide a higher timeout than the default (20s) via a command-line argument like e.g. `--timeout=60`, however, I doubt that a too-low timeout is the issue.

A few questions to help troubleshoot this:
- Are you able to access the live time series on your computer via the vendor-provided monitoring tool? 
- Which operating system are you on? And if Windows, did you install the PyBluez build from the S3 location?  
- What's the exact model of your device?
- what exact Python version are you using?
- Does the program work when you invoke it via the `run.cmd` or `run.sh` file?

**Comment by jh510** [comment]
Update: I got the stream working on a windows machine (with and without conda) following the instructions. I will work on figuring out the problem with my Mac.

Response to @chkothe questions:
1). Yes, I am able to get data through AcqKnowledge software
2). Mac OS Catalina
3).  Biopac Bioharness 3 BT
- Boot Software Version: v1.3.1.0
- Hardware Part Number: 9800 0189v9p
- Boot Part Number: 9500 0084
4). Python 3.7.9
5).  The program runs with the same log info displayed.

**Comment by chkothe** [comment]
Ok, great! 

PyBluez should be working on the Mac, although I haven't been able to test it personally. If your Python is compiled with Bluetooth support (I'm not sure if yours is), then one could potentially try to create the socket like this 
```
import socket
sock = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM, socket.BTPROTO_RFCOMM)
```
instead of the equivalent line at https://github.com/labstreaminglayer/App-Zephyr/blob/main/core/bluetooth.py#L82.

If you want to give this a try and it's working, let me know, then we could special-case it like that for the mac (e.g., something like `if hasattr(socket, 'AF_BLUETOOTH')`).

**Comment by jh510** [comment]
The device is not working with the vendor software at the moment, so this might be something wrong with device. I am working with the vendor to see if we can get it fixed. I will update once the vendor gets back to me. 

The socket code did not work, but I am thinking this is more of a hardware problem for some reason.

**Comment by chkothe** [comment]
We've confirmed that there's a Bluetooth compatibility issue with current Mac OS and various Python (and PyBlueZ) builds. Most likely we'll have to wait until the upstream support is working (or find a drop-in replacement that works on this OS). This has been noted under Known Issues

**Comment by chkothe** [comment]
Closing the issue. Once upstream Python BLE dependencies on Mac OS improve and/or an alternative is found, the app can be updated to use those.
